# Generated by Django 5.2 on 2025-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('body_md', models.TextField(verbose_name='متن (Markdown)')),
                ('video_url', models.URLField(blank=True, verbose_name='آدرس ویدیو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پُست',
                'verbose_name_plural': 'پُست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
